project:
  type: website
  output-dir: docs

author:
  name: "Josef Fruehwald"
  url: "https://jofrhwld.github.io/"

website:
  title: "Statistical Rethinking Workthrough Blog"
  navbar:
    right:
      - about.qmd
      - text: "blog"
        href: "https://jofrhwld.github.io/blog/"
  sidebar:
    contents: posts
  twitter-card: true
  open-graph: true

format:
  html:
    theme: sandstone
    css: styles.css
    code-annotations: hover
    tbl-cap-location: margin
    fig-width: 6
    fig-height: 4
    fig-cap-location: margin


knitr:
  opts_chunk:
    message: false
    warning: false
    dev: "ragg_png"

editor: visual

